### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'model'

### ISSUE THREAD

**Issue by dpasch01** [ZagHe568/pacte-polarized-topics-detection#2]
Hello, 

I followed your exact instructions and got the following error when running `python run.py`.
I also tried with the provided data and the locally generated ones.

It works if I change the init_train=0 to init_train=1. Is this correct?

`
    Traceback (most recent call last):
    File "engine.py", line 519, in <module>
    engine.get_polarization()
    File "engine.py", line 338, in get_polarization
    doc_embeddings = self.calc_embeddings(True)
    File "engine.py", line 209, in calc_embeddings
    self.model.eval()
    AttributeError: 'Engine' object has no attribute 'model'
`

**Comment by zihaohe123** [comment]
oh right you should change it to 1! I'll change it.
